### ISSUE TITLE
How to set up a server-client socket 

### ISSUE THREAD

**Issue by it19862** [InitPHP/Socket#1]
I'm trying to install a server
I use an OpenServer.
Done.

downloaded the archive;
placed files in a folder `c:\openserver\domains\SocketInitPHPGithub`;
from composer.json deleted `"name": "initphp/socket",`
because it gave an error the next step, then deleted it according to the recommendations on some forum.
Now my folders look like in the picture.

**Question.**
How to use it? What should I add?
How to start the server?
How to start the client?

**Pictute-1**
![27 05 2022_17-55-32](https://user-images.githubusercontent.com/18245828/170770408-7d751819-5b3f-4dca-8492-4731b6abf451.png)

**Pictute-2**
![27 05 2022_17-55-52](https://user-images.githubusercontent.com/18245828/170770436-5a38efaa-be8c-46dd-b0e7-5976867b42a2.png)

**Comment by muhammetsafak** [comment]
The Readme.md file contains the necessary explanation.
 
Server : [https://github.com/InitPHP/Socket#socket-server](https://github.com/InitPHP/Socket#socket-server)
Client : [https://github.com/InitPHP/Socket#socket-client](https://github.com/InitPHP/Socket#socket-client)
 
The composer.json content is related to the PHP package manager composer. This library uses composer's autoload in PSR-4 standards. Required so that the files containing the classes can be loaded automatically.
In your use case, start a terminal in the directory you are working in and issue the `composer dump-autoload` command. You can learn more about Composer on its official website. [https://getcomposer.org/](https://getcomposer.org/)
